# -*- coding: utf-8 -*-
def add(p, P, ORC):
    p.fix(P + "/sig/tls/name", old=u"(없음)",
          new=u"(직접 없음) · 전이 도달 9종: make_gank_battle(version≥2 경로)→ MAX_RANGE_CACHE · FIGHT_KIT_RANGE_CACHE · DIE_TICK_CACHE · ATTACK_DMG_CACHE · RESOLVE_FIGHT_CACHE · LAST_STAND_MEMO · CAMP_POS_MEMO(game_core) · BATTLE_RECENCY(game_core) / lane_path(L369)→ LANE_PATH_MEMO(game_core)",
          evidence=u"IR 호출 그래프 전이 탐색(스크래치 tlsreach2.py · _gaibc+_gcbc define 36,096 색인 · LocalKey::with 의 anon 함수포인터 상수(예 m02.ll:273 `@anon.… = constant ptr @…CAST_BEAMSs_0s_0…call_once`)까지 추적 · BattleSubPlan::action_candidates 로 CAST_BEAMS 검출 확인) — 경로: make_gank_battle(m08.ll:94354)→open_chase_race_hopeless(m10.ll:47705)→max_range_cached→MAX_RANGE_CACHE / →BattlePlan::update(m10.ll:23429)→{fight_kit_range_cached→FIGHT_KIT_RANGE_CACHE, check_kill_die_tick→DIE_TICK_CACHE→…uncached→enemy_minion_wave_risk→ATTACK_DMG_CACHE, MapDef::camp_pos→CAMP_POS_MEMO, battle_recency→BATTLE_RECENCY, defense_nexus nexus_…→LAST_STAND_MEMO, fight_model resolve_…→RESOLVE_FIGHT_CACHE} / lane_path(m08.ll:95470 호출)→LANE_PATH_MEMO(g11.ll)",
          behavior_change=False, found_by="new", kind=u"보강")
    p.fix(P + "/sig/tls/role", old=u"직접 접점 0",
          new=u"직접 접점 0 · 전이 접점은 make_gank_battle(version≥2 에서만: open_chase_race_hopeless 1회 → 아니면 BattlePlan::new+update)과 L369 lane_path 뿐 — check_kill(m13.ll:54538 · 45노드)·get_die_tick_player(m09.ll:52061 · 30노드)·BattlePlan::new(m10.ll:23214 · 12노드)·is_recent_visible·is_in_jungle_area·near_jungle_bush·get_start_position·iter_towers_without_nexus·Entity::distance·Effect::range_adjust·add_text 은 전이 TLS 0",
          evidence=u"tlsreach2.py BFS: 위 콜리 서브트리에 thread_local 전역 참조 0 (vtable 간접 호출 is_visible/get_entity_by_id/tick 은 정적 추적 밖). v47_siege_stance(SIEGE_STANCE_CACHE)·v48_cast_beams(CAST_BEAMS)·champion_hp_value(HP_VALUE_MEMO)·position_eval_at(POS_EVAL_CACHE)·interaction_score(INTER_CTX)는 직접은 물론 **전이로도 도달 불가**(CAST_BEAMS 의 m02.ll:34749 는 BattleSubPlan::action_candidates 소속)",
          behavior_change=False, found_by="new", kind=u"보강")
    p.fix(P + "/sig/tls/call_conditions",
          old=u"TLS 가 있다면 콜리 내부(make_gank_battle · check_kill · get_die_tick_player · BattlePlan::new) — 호출 순서는 logic 의 줄 순서(L127→L136→L212/214/217/221→L225→L227→L241) 그대로이며 한 호출에서 Some 이 나오면 즉시 반환하므로 그 뒤 콜리는 실행되지 않는다",
          new=u"TLS 작성자는 두 콜리 경유뿐: ① L369 lane_path→LANE_PATH_MEMO — L101/L127/L136 에서 반환하지 않았고 reference 가 None 일 때(front_minion None 이거나 dist²(front,nexus) < dist²(nearest_tower,nexus), 95463) 1회 ② make_gank_battle 7사이트(L127→L212/214/217/221(후보 e 슬롯 순)→L227→L241) — version≥2 에서만 open_chase_race_hopeless(→MAX_RANGE_CACHE) 1회, 거짓이면 BattlePlan::update(→FIGHT_KIT_RANGE·DIE_TICK·ATTACK_DMG·RESOLVE_FIGHT·LAST_STAND·CAMP_POS·BATTLE_RECENCY, 조건은 update 명세 소관); 한 사이트가 Some 이면 즉시 반환하지만 **None(-1)이면 다음 사이트로 이어져 같은 캐시가 한 next_plan 호출 안에서 여러 번 갱신될 수 있다**(오라클 E6/E7/F1b: hopeless 참 → 다음 분기 진행). check_kill·get_die_tick_player·BattlePlan::new 는 전이 TLS 0 이라 version≤1 경로는 lane_path 외 TLS 접점이 없다",
          evidence=u"m08.ll:95470 lane_path 호출은 216 블록(preds 170·171·180 = front None/filter 탈락) 에서만 · make_gank_battle 94368 `icmp ugt %1, 1` 로 version 분기 · 94426 open_chase_race_hopeless · 94459 BattlePlan::update · 본체 97045/97828/97833/97902/97907/98186/98321 `icmp eq -1` 후속 진행",
          behavior_change=False, found_by="new", kind=u"보강")
