bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
epoch = 2
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
keep_tokens = 1
learning_rate = 0.0001
logging_dir = "C:\\tfm2mods\\sylas_art\\lora_dataset\\log"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 0.1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 2516
min_bucket_reso = 256
mixed_precision = "fp16"
network_alpha = 16
network_args = []
network_dim = 32
network_module = "networks.lora"
network_train_unet_only = true
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW8bit"
output_dir = "C:\\tfm2mods\\sylas_art\\lora_dataset\\model"
output_name = "tfm2_sprite"
pretrained_model_name_or_path = "C:/Users/dev/Downloads/StabilityMatrix-win-x64/Data/Models/StableDiffusion/pixelArtSpriteDiffusion_safetensors.safetensors"
prior_loss_weight = 1
resolution = "512,512"
sample_prompts = "C:\\tfm2mods\\sylas_art\\lora_dataset\\model\\sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
train_batch_size = 2
train_data_dir = "C:/tfm2mods/sylas_art/lora_dataset/img"
unet_lr = 0.0001
wandb_run_name = "tfm2_sprite"
xformers = true
