//! 자동 생성 — i18n 표시명 테이블. 직접 수정 금지.
//! 소스 = bundle champion.i18n / 생성기 = gen_names2.py (세션 스크래치패드).
//! 로케일 17종 전체, 로케일 간 중복 표기는 병합, 충돌 표기는 제외.

/// 챔피언 표시명 -> champ id
pub static NAME2ID: &[(&str, &str)] = &[
    ("Albtraum", "nightmare"),
    ("Alchemik", "alchemist"),
    ("Alchemist", "alchemist"),
    ("Alchimista", "alchemist"),
    ("Alchimiste", "alchemist"),
    ("Alquimista", "alchemist"),
    ("Android", "android"),
    ("Androide", "android"),
    ("Androïde", "android"),
    ("Arbaletçi", "crossbowman"),
    ("Arbalétrier", "crossbowman"),
    ("Archer", "archer"),
    ("Armbrustschütze", "crossbowman"),
    ("Arquero", "archer"),
    ("Asker", "soldier"),
    ("Ateş büyücüsü", "pyromancer"),
    ("Avcı", "hunter"),
    ("Ağır piyade", "hammerer"),
    ("Bailarina", "dancer"),
    ("Balestriere", "crossbowman"),
    ("Ballestero", "crossbowman"),
    ("Bard", "bard"),
    ("Barde", "bard"),
    ("Bardo", "bard"),
    ("Bariyer büyücüsü", "barrier_magician"),
    ("Barrier Mage", "barrier_magician"),
    ("Barrier Magician", "barrier_magician"),
    ("Barrieren-Magier", "barrier_magician"),
    ("Barrière magiër", "barrier_magician"),
    ("Belagerungsbrecher", "siege_breaker"),
    ("Belegering breker", "siege_breaker"),
    ("Berserker", "berserker"),
    ("Besteiro", "crossbowman"),
    ("Betoveraar", "enchanter"),
    ("Beul", "executioner"),
    ("Beyaz büyücü", "white_mage"),
    ("Bliksemmagiër", "lightning_mage"),
    ("Blitzmagier", "lightning_mage"),
    ("Bogenschütze", "archer"),
    ("Bombacı", "bomber"),
    ("Bombardero", "bomber"),
    ("Bombardier", "bomber"),
    ("Bomber", "bomber"),
    ("Boogschutter", "archer"),
    ("Boomerang Hunter", "boomerang_hunter"),
    ("Boomerang jager", "boomerang_hunter"),
    ("Briseur de siège", "siege_breaker"),
    ("Bumerang avcısı", "boomerang_hunter"),
    ("Bumerang-Jäger", "boomerang_hunter"),
    ("Buz büyücüsü", "ice_mage"),
    ("Büyü şövalyesi", "magic_knight"),
    ("Büyücü", "enchanter"),
    ("Caballero", "knight"),
    ("Caballero mágico", "magic_knight"),
    ("Cauchemar", "nightmare"),
    ("Cavalerie ridder", "cavalry_knight"),
    ("Cavalry", "cavalry_knight"),
    ("Cavalry Knight", "cavalry_knight"),
    ("Cazador", "hunter"),
    ("Cazador de bumerán", "boomerang_hunter"),
    ("Cazador de dardos venenosos", "poison_dart_hunter"),
    ("Cellat", "executioner"),
    ("Chaman vaudou", "voodoo_shaman"),
    ("Chamán vudú", "voodoo_shaman"),
    ("Chasseur", "hunter"),
    ("Chasseur de boomerang", "boomerang_hunter"),
    ("Chasseur de fléchettes empoisonnées", "poison_dart_hunter"),
    ("Chef", "chef"),
    ("Chevalier", "knight"),
    ("Chevalier de cavalerie", "cavalry_knight"),
    ("Chevalier magique", "magic_knight"),
    ("Circus Blade", "circus_blade"),
    ("Circusmes", "circus_blade"),
    ("Clown", "clown"),
    ("Combattant", "fighter"),
    ("Crossbowman", "crossbowman"),
    ("Cuchilla Circense", "circus_blade"),
    ("Dancer", "dancer"),
    ("Danseres", "dancer"),
    ("Danseuse", "dancer"),
    ("Dansçı", "dancer"),
    ("Dark Mage", "dark_mage"),
    ("Demon", "demon"),
    ("Demonio", "demon"),
    ("Doble espada", "dual_blader"),
    ("Dokkaebi", "dokkaebi"),
    ("Donkere magiër", "dark_mage"),
    ("Doppelklingen-Kämpfer", "dual_blader"),
    ("Double lame", "dual_blader"),
    ("Druid", "druid"),
    ("Druida", "druid"),
    ("Druide", "druid"),
    ("Druïde", "druid"),
    ("Dual Blader", "dual_blader"),
    ("Dubbele zwaardenvechter", "dual_blader"),
    ("Dunkler Magier", "dark_mage"),
    ("Dämon", "demon"),
    ("Démon", "demon"),
    ("Dövüşçü", "fighter"),
    ("Eismagier", "ice_mage"),
    ("Ejecutor", "executioner"),
    ("Encantador", "enchanter"),
    ("Enchanter", "enchanter"),
    ("Enchanteur", "enchanter"),
    ("Engizisyoncu", "inquisitor"),
    ("Espadachín", "swordman"),
    ("Esprit gardien", "guardian_spirit"),
    ("Executioner", "executioner"),
    ("Exorcist", "exorcist"),
    ("Exorcista", "exorcist"),
    ("Exorciste", "exorcist"),
    ("Exorzist", "exorcist"),
    ("Exécuteur", "executioner"),
    ("Fantasma", "ghost"),
    ("Fantôme", "ghost"),
    ("Fighter", "fighter"),
    ("Gambler", "gambler"),
    ("Geest", "ghost"),
    ("Geest oproeper", "spirit_caller"),
    ("Geestbeschermer", "guardian_spirit"),
    ("Gefangener", "prisoner"),
    ("Geist", "ghost"),
    ("Geisterrufer", "spirit_caller"),
    ("Gevangene", "prisoner"),
    ("Ghost", "ghost"),
    ("Gifpijl jager", "poison_dart_hunter"),
    ("Giftpfeil-Jäger", "poison_dart_hunter"),
    ("Gokker", "gambler"),
    ("Guardian Spirit", "guardian_spirit"),
    ("Guardián Espiritual", "guardian_spirit"),
    ("Guerrero de pértiga", "pole_warrior"),
    ("Guerrier de perche", "pole_warrior"),
    ("Gunner", "gunner"),
    ("Gölge büyücüsü", "shadowmancer"),
    ("Hammerer", "hammerer"),
    ("Hayalet", "ghost"),
    ("Henker", "executioner"),
    ("Hitman", "hitman"),
    ("Hombre lobo", "werewolf"),
    ("Hunter", "hunter"),
    ("Ice Mage", "ice_mage"),
    ("Ijsmagiër", "ice_mage"),
    ("Illusionist", "illusionist"),
    ("Illusionniste", "illusionist"),
    ("Ilusionista", "illusionist"),
    ("Incubo", "nightmare"),
    ("Infanterie lourde", "hammerer"),
    ("Infantería pesada", "hammerer"),
    ("Inquisidor", "inquisitor"),
    ("Inquisiteur", "inquisitor"),
    ("Inquisitor", "inquisitor"),
    ("Invocador de espíritus", "spirit_caller"),
    ("Invocateur d'esprit", "spirit_caller"),
    ("Jager", "hunter"),
    ("Jiangshi", "jiangshi"),
    ("Jinete de Caballería", "cavalry_knight"),
    ("Joueur", "gambler"),
    ("Jugador", "gambler"),
    ("Jäger", "hunter"),
    ("Kabus", "nightmare"),
    ("Kahuna", "priest"),
    ("Kalkan taşıyıcısı", "shield_bearer"),
    ("Karanlık büyücü", "dark_mage"),
    ("Kavallerieritter", "cavalry_knight"),
    ("Keşiş", "monk"),
    ("Kilokilo One", "sand_mage"),
    ("Knight", "knight"),
    ("Koa Pahi", "swordman"),
    ("Koch", "chef"),
    ("Koszmar", "nightmare"),
    ("Kruisboogschutter", "crossbowman"),
    ("Kum Büyücüsü", "sand_mage"),
    ("Kumarbaz", "gambler"),
    ("Kurt adam", "werewolf"),
    ("Kusznik", "crossbowman"),
    ("Kutup savaşçısı", "pole_warrior"),
    ("Kuşatma kırıcı", "siege_breaker"),
    ("Kämpfer", "fighter"),
    ("Kāhea ʻUhane", "spirit_caller"),
    ("Kılıç ustası", "swordman"),
    ("Kırbaç ustası", "whip_master"),
    ("Lame de Cirque", "circus_blade"),
    ("Lancer", "lancer"),
    ("Lancero", "lancer"),
    ("Lancetier", "lancer"),
    ("Lancier", "lancer"),
    ("Lanzer", "lancer"),
    ("Lightning Mage", "lightning_mage"),
    ("Loup-garou", "werewolf"),
    ("Luchador", "fighter"),
    ("Maestro del látigo", "whip_master"),
    ("Mag piasku", "sand_mage"),
    ("Mage blanc", "white_mage"),
    ("Mage de barrière", "barrier_magician"),
    ("Mage de foudre", "lightning_mage"),
    ("Mage de glace", "ice_mage"),
    ("Mage des ombres", "shadowmancer"),
    ("Mage du sable", "sand_mage"),
    ("Mage du vent", "wind_mage"),
    ("Mage noir", "dark_mage"),
    ("Magic Knight", "magic_knight"),
    ("Magieritter", "magic_knight"),
    ("Magische ridder", "magic_knight"),
    ("Mago blanco", "white_mage"),
    ("Mago da Areia", "sand_mage"),
    ("Mago de arena", "sand_mage"),
    ("Mago de barrera", "barrier_magician"),
    ("Mago de hielo", "ice_mage"),
    ("Mago de rayo", "lightning_mage"),
    ("Mago de sombras", "shadowmancer"),
    ("Mago de viento", "wind_mage"),
    ("Mago della sabbia", "sand_mage"),
    ("Mago oscuro", "dark_mage"),
    ("Mahkum", "prisoner"),
    ("Maître du fouet", "whip_master"),
    ("Mea Hana Kemia", "alchemist"),
    ("Mea Pana Kea", "crossbowman"),
    ("Mea Pana Pua", "archer"),
    ("Moemoeā", "nightmare"),
    ("Moine", "monk"),
    ("Monje", "monk"),
    ("Monk", "monk"),
    ("Monnik", "monk"),
    ("Médecin de la peste", "plague_doctor"),
    ("Médico de la plaga", "plague_doctor"),
    ("Mönch", "monk"),
    ("Mızrakçı", "lancer"),
    ("Nachtmerrie", "nightmare"),
    ("Necromancer", "necromancer"),
    ("Nekromanser", "necromancer"),
    ("Nekromant", "necromancer"),
    ("Nhà giả kim", "alchemist"),
    ("Nightmare", "nightmare"),
    ("Nigromante", "necromancer"),
    ("Ninja", "ninja"),
    ("Nécromancien", "necromancer"),
    ("Nỏ thủ", "crossbowman"),
    ("Oger", "ogre"),
    ("Ogre", "ogre"),
    ("Ogro", "ogre"),
    ("Okçu", "archer"),
    ("Ozan", "bard"),
    ("Palyaço", "clown"),
    ("Payaso", "clown"),
    ("Peitschenmeister", "whip_master"),
    ("Pesadelo", "nightmare"),
    ("Pesadilla", "nightmare"),
    ("Pestdoktor", "plague_doctor"),
    ("Pháp sư Cát", "sand_mage"),
    ("Piromante", "pyromancer"),
    ("Pitonesa", "pythoness"),
    ("Plaagdokter", "plague_doctor"),
    ("Plague Doctor", "plague_doctor"),
    ("Poison Dart", "poison_dart_hunter"),
    ("Poison Dart Hunter", "poison_dart_hunter"),
    ("Poisondart Hunter", "poison_dart_hunter"),
    ("Pole Warrior", "pole_warrior"),
    ("Pool strijder", "pole_warrior"),
    ("Portador de escudo", "shield_bearer"),
    ("Porteur de bouclier", "shield_bearer"),
    ("Priest", "priest"),
    ("Priester", "priest"),
    ("Priestess", "priest"),
    ("Prisioner", "prisoner"),
    ("Prisionero", "prisoner"),
    ("Prisoner", "prisoner"),
    ("Prisonnier", "prisoner"),
    ("Prêtre", "priest"),
    ("Pyromancer", "pyromancer"),
    ("Pyromancien", "pyromancer"),
    ("Pyromant", "pyromancer"),
    ("Pythoness", "pythoness"),
    ("Pythonisse", "pythoness"),
    ("Rahip", "priest"),
    ("Ridder", "knight"),
    ("Ritter", "knight"),
    ("Rompedor de asedio", "siege_breaker"),
    ("Ruh Koruyucusu", "guardian_spirit"),
    ("Ruh çağıran", "spirit_caller"),
    ("Rüzgar büyücüsü", "wind_mage"),
    ("Sacerdote", "priest"),
    ("Sand Mage", "sand_mage"),
    ("Sandmagier", "sand_mage"),
    ("Schaduwmagiër", "shadowmancer"),
    ("Schattenmagier", "shadowmancer"),
    ("Schilddrager", "shield_bearer"),
    ("Schildträger", "shield_bearer"),
    ("Schutter", "gunner"),
    ("Schutzgeist", "guardian_spirit"),
    ("Schwerer Infanterist", "hammerer"),
    ("Schwertkämpfer", "swordman"),
    ("Schütze", "gunner"),
    ("Shadowmancer", "shadowmancer"),
    ("Shield Bearer", "shield_bearer"),
    ("Shrine Maiden", "pythoness"),
    ("Sicario", "hitman"),
    ("Siege Breaker", "siege_breaker"),
    ("Silahlı", "gunner"),
    ("Simyacı", "alchemist"),
    ("Sirk Bıçağı", "circus_blade"),
    ("Sniper", "soldier"),
    ("Soldaat", "soldier"),
    ("Soldado", "soldier"),
    ("Soldat", "soldier"),
    ("Soldier", "soldier"),
    ("Spieler", "gambler"),
    ("Spirit Caller", "spirit_caller"),
    ("Stangenkrieger", "pole_warrior"),
    ("Swordman", "swordman"),
    ("Swordsman", "swordman"),
    ("Süvari şövalye", "cavalry_knight"),
    ("Taoist", "taoist"),
    ("Taoísta", "taoist"),
    ("Taoïst", "taoist"),
    ("Taoïste", "taoist"),
    ("Tetikçi", "hitman"),
    ("Tirador", "gunner"),
    ("Tireur", "gunner"),
    ("Tueur à gages", "hitman"),
    ("Tänzerin", "dancer"),
    ("Vampier", "vampire"),
    ("Vampir", "vampire"),
    ("Vampire", "vampire"),
    ("Vampiro", "vampire"),
    ("Veba doktoru", "plague_doctor"),
    ("Vechter", "fighter"),
    ("Verzauberer", "enchanter"),
    ("Voodoo Shaman", "voodoo_shaman"),
    ("Voodoo sjamaan", "voodoo_shaman"),
    ("Voodoo-Schamane", "voodoo_shaman"),
    ("Vudu şamanı", "voodoo_shaman"),
    ("Weerwolf", "werewolf"),
    ("Weißer Magier", "white_mage"),
    ("Werewolf", "werewolf"),
    ("Werwolf", "werewolf"),
    ("Whip Master", "whip_master"),
    ("White Mage", "white_mage"),
    ("Wind Mage", "wind_mage"),
    ("Windmagier", "wind_mage"),
    ("Windmagiër", "wind_mage"),
    ("Witte magiër", "white_mage"),
    ("Yıldırım büyücüsü", "lightning_mage"),
    ("Zandmagiër", "sand_mage"),
    ("Zehirli ok avcısı", "poison_dart_hunter"),
    ("Zirkusklinge", "circus_blade"),
    ("Zwaardvechter", "swordman"),
    ("Zware infanterie", "hammerer"),
    ("Zweep meester", "whip_master"),
    ("Ác Mộng", "nightmare"),
    ("Çift kılıçlı", "dual_blader"),
    ("Épéiste", "swordman"),
    ("İllüzyonist", "illusionist"),
    ("Şef", "chef"),
    ("Şeytan", "demon"),
    ("Şeytan kovucu", "exorcist"),
    ("Şövalye", "knight"),
    ("Азартный игрок", "gambler"),
    ("Акробат", "circus_blade"),
    ("Алхимик", "alchemist"),
    ("Андроид", "android"),
    ("Арбалетчик", "crossbowman"),
    ("Бард", "bard"),
    ("Берсерк", "berserker"),
    ("Боец", "fighter"),
    ("Вампир", "vampire"),
    ("Всадница", "cavalry_knight"),
    ("Демон", "demon"),
    ("Доккаеби", "dokkaebi"),
    ("Друид", "druid"),
    ("Дух-хранитель", "guardian_spirit"),
    ("Дуэлянт", "dual_blader"),
    ("Жрица духов", "pythoness"),
    ("Заклинатель барьеров", "barrier_magician"),
    ("Защитник", "shield_bearer"),
    ("Иллюзионист", "illusionist"),
    ("Инквизитор", "inquisitor"),
    ("Клоун", "clown"),
    ("Копейщик", "lancer"),
    ("Кошмар", "nightmare"),
    ("Криомант", "ice_mage"),
    ("Лучник", "archer"),
    ("Маг воздуха", "wind_mage"),
    ("Маг песка", "sand_mage"),
    ("Маг света", "white_mage"),
    ("Маг теней", "shadowmancer"),
    ("Магический мечник", "magic_knight"),
    ("Мастер кнута", "whip_master"),
    ("Мастер посоха", "pole_warrior"),
    ("Мечник", "swordman"),
    ("Молотобоец", "hammerer"),
    ("Монах", "monk"),
    ("Некромант", "necromancer"),
    ("Ниндзя", "ninja"),
    ("Оборотень", "werewolf"),
    ("Огр", "ogre"),
    ("Отшельник", "taoist"),
    ("Охотник", "hunter"),
    ("Охотник с бумерангом", "boomerang_hunter"),
    ("Палач", "executioner"),
    ("Пиромант", "pyromancer"),
    ("Повар", "chef"),
    ("Повелитель духов", "spirit_caller"),
    ("Повелитель молний", "lightning_mage"),
    ("Подрывник", "bomber"),
    ("Призрак", "ghost"),
    ("Проклинатель", "voodoo_shaman"),
    ("Разрушитель", "siege_breaker"),
    ("Рыцарь", "knight"),
    ("Священник", "priest"),
    ("Снайпер", "soldier"),
    ("Стрелок", "gunner"),
    ("Танцовщица", "dancer"),
    ("Темный маг", "dark_mage"),
    ("Узник", "prisoner"),
    ("Хитман", "hitman"),
    ("Цзянши", "jiangshi"),
    ("Чародей", "enchanter"),
    ("Чумной доктор", "plague_doctor"),
    ("Экзорцист", "exorcist"),
    ("Ядовитый охотник", "poison_dart_hunter"),
    ("กันสลิงเกอร์", "gunner"),
    ("คลีริก", "priest"),
    ("จอมเวทขาว", "white_mage"),
    ("จอมเวทดำ", "dark_mage"),
    ("จอมเวททราย", "sand_mage"),
    ("จิตพิทักษ์", "guardian_spirit"),
    ("ชาโดว์เมจ", "shadowmancer"),
    ("ดรูอิด", "druid"),
    ("ดวลเบลดเดอร์", "dual_blader"),
    ("ตัวตลก", "clown"),
    ("ทหารม้า", "cavalry_knight"),
    ("นักดาบ", "swordman"),
    ("นักธนู", "archer"),
    ("นักเต้น", "dancer"),
    ("นักเล่นแร่แปรธาตุ", "alchemist"),
    ("นักโทษ", "prisoner"),
    ("นินจา", "ninja"),
    ("บาร์ด", "bard"),
    ("บูมเมอแรงฮันเตอร์", "boomerang_hunter"),
    ("ผู้ควบคุมภูต", "spirit_caller"),
    ("ผู้ใช้ค่ายกล", "barrier_magician"),
    ("ผู้ใช้เข็มพิษ", "poison_dart_hunter"),
    ("ผู้ใช้แส้", "whip_master"),
    ("ฝันร้าย", "nightmare"),
    ("พลทำลายป้อม", "siege_breaker"),
    ("พลระเบิด", "bomber"),
    ("พลหน้าไม้", "crossbowman"),
    ("พลองเหล็ก", "pole_warrior"),
    ("พลเดินเท้าหนัก", "hammerer"),
    ("พลโล่", "shield_bearer"),
    ("พลไรเฟิล", "soldier"),
    ("มังค์", "monk"),
    ("มิโกะ", "pythoness"),
    ("วูดูด็อกเตอร์", "voodoo_shaman"),
    ("สเปลเบลด", "magic_knight"),
    ("อะโครแบท", "circus_blade"),
    ("อินควิซิเตอร์", "inquisitor"),
    ("อิลลูชันนิสต์", "illusionist"),
    ("ฮันเตอร์", "hunter"),
    ("ฮิตแมน", "hitman"),
    ("เจียงซือ", "jiangshi"),
    ("เชฟ", "chef"),
    ("เดมอน", "demon"),
    ("เนโครแมนเซอร์", "necromancer"),
    ("เบอร์เซิร์กเกอร์", "berserker"),
    ("เพชฌฆาต", "executioner"),
    ("เอนแชนเตอร์", "enchanter"),
    ("เอ็กซอร์ซิสต์", "exorcist"),
    ("แกมเบลอร์", "gambler"),
    ("แกร็ปเลอร์", "fighter"),
    ("แพทย์กาฬโรค", "plague_doctor"),
    ("แลนเซอร์", "lancer"),
    ("แวมไพร์", "vampire"),
    ("แวร์วูล์ฟ", "werewolf"),
    ("แอนดรอยด์", "android"),
    ("แอร์มันเซอร์", "wind_mage"),
    ("โกสต์", "ghost"),
    ("โดซา", "taoist"),
    ("โทแกบี", "dokkaebi"),
    ("โอเกอร์", "ogre"),
    ("ไครโอมันเซอร์", "ice_mage"),
    ("ไนท์", "knight"),
    ("ไพโรแมนเซอร์", "pyromancer"),
    ("ไลท์นิงเมจ", "lightning_mage"),
    ("アンドロイド", "android"),
    ("エクソシスト", "exorcist"),
    ("エンチャンター", "enchanter"),
    ("オーガ", "ogre"),
    ("ガンナー", "gunner"),
    ("キョンシー", "jiangshi"),
    ("サーカスブレード", "circus_blade"),
    ("デュアルブレーダー", "dual_blader"),
    ("ドッケビ", "dokkaebi"),
    ("ドルイド", "druid"),
    ("ネクロマンサー", "necromancer"),
    ("ハンター", "hunter"),
    ("ヒットマン", "hitman"),
    ("ブードゥーシャーマン", "voodoo_shaman"),
    ("ブーメランハンター", "boomerang_hunter"),
    ("モンク", "monk"),
    ("人造人", "android"),
    ("僧侣", "monk"),
    ("僧侶", "monk"),
    ("僵尸", "jiangshi"),
    ("冰霜法師", "ice_mage"),
    ("処刑人", "executioner"),
    ("剑客", "swordman"),
    ("剣士", "swordman"),
    ("劍士", "swordman"),
    ("厨师", "chef"),
    ("双刀客", "dual_blader"),
    ("吟游诗人", "bard"),
    ("吟遊詩人", "bard"),
    ("吸血鬼", "vampire"),
    ("囚人", "prisoner"),
    ("囚徒", "prisoner"),
    ("回旋镖手", "boomerang_hunter"),
    ("处刑人", "executioner"),
    ("夢魔", "nightmare"),
    ("夢魘", "nightmare"),
    ("守護霊", "guardian_spirit"),
    ("守護靈", "guardian_spirit"),
    ("审判官", "inquisitor"),
    ("寒冰法师", "ice_mage"),
    ("小丑", "clown"),
    ("小銃手", "soldier"),
    ("巨盾兵", "shield_bearer"),
    ("巨盾衛士", "shield_bearer"),
    ("巫女", "pythoness"),
    ("巫毒萨满", "voodoo_shaman"),
    ("巫毒薩滿", "voodoo_shaman"),
    ("幻影術師", "illusionist"),
    ("幻术师", "illusionist"),
    ("幻術師", "illusionist"),
    ("幽灵", "ghost"),
    ("幽霊", "ghost"),
    ("幽靈", "ghost"),
    ("廚師", "chef"),
    ("弓使い", "archer"),
    ("弓箭手", "archer"),
    ("弩手", "crossbowman"),
    ("影術師", "shadowmancer"),
    ("德魯伊", "druid"),
    ("德鲁伊", "druid"),
    ("忍者", "ninja"),
    ("快枪手", "gunner"),
    ("恶魔", "demon"),
    ("悪魔", "demon"),
    ("惡魔", "demon"),
    ("戍魂灵", "guardian_spirit"),
    ("戏刃师", "circus_blade"),
    ("戲刃師", "circus_blade"),
    ("攻城兵", "siege_breaker"),
    ("料理人", "chef"),
    ("暗影法师", "shadowmancer"),
    ("暗影法師", "shadowmancer"),
    ("机器人", "android"),
    ("杀手", "hitman"),
    ("格斗家", "fighter"),
    ("格闘家", "fighter"),
    ("格鬥家", "fighter"),
    ("梦魇", "nightmare"),
    ("棒行者", "pole_warrior"),
    ("棒術師", "pole_warrior"),
    ("槍手", "gunner"),
    ("槍術師", "lancer"),
    ("步枪手", "soldier"),
    ("步槍手", "soldier"),
    ("死灵法师", "necromancer"),
    ("死靈法師", "necromancer"),
    ("殭屍", "jiangshi"),
    ("毒針獵手", "poison_dart_hunter"),
    ("毒針術師", "poison_dart_hunter"),
    ("毒针猎手", "poison_dart_hunter"),
    ("氷術師", "ice_mage"),
    ("沙术师", "sand_mage"),
    ("沙術師", "sand_mage"),
    ("火炎術師", "pyromancer"),
    ("火焰法师", "pyromancer"),
    ("火焰法師", "pyromancer"),
    ("炼金术师", "alchemist"),
    ("爆弾兵", "bomber"),
    ("爆破手", "bomber"),
    ("牧师", "priest"),
    ("牧師", "priest"),
    ("狂战士", "berserker"),
    ("狂戦士", "berserker"),
    ("狂戰士", "berserker"),
    ("狼人", "werewolf"),
    ("狼人間", "werewolf"),
    ("異端審判官", "inquisitor"),
    ("異端審問官", "inquisitor"),
    ("疫病医者", "plague_doctor"),
    ("瘟疫医生", "plague_doctor"),
    ("瘟疫醫生", "plague_doctor"),
    ("白魔法师", "white_mage"),
    ("白魔法師", "white_mage"),
    ("白魔術師", "white_mage"),
    ("盾兵", "shield_bearer"),
    ("石弓兵", "crossbowman"),
    ("砂術師", "sand_mage"),
    ("破城者", "siege_breaker"),
    ("精灵使", "spirit_caller"),
    ("精霊師", "spirit_caller"),
    ("精靈使", "spirit_caller"),
    ("結界師", "barrier_magician"),
    ("结界术师", "barrier_magician"),
    ("聖職者", "priest"),
    ("職業殺手", "hitman"),
    ("舞姫", "dancer"),
    ("舞姬", "dancer"),
    ("舞者", "dancer"),
    ("處刑人", "executioner"),
    ("賭博師", "gambler"),
    ("賭徒", "gambler"),
    ("赌徒", "gambler"),
    ("赤魇", "dokkaebi"),
    ("迴旋鏢獵人", "boomerang_hunter"),
    ("追猎者", "hunter"),
    ("追獵者", "hunter"),
    ("道化師", "clown"),
    ("道士", "taoist"),
    ("重歩兵", "hammerer"),
    ("重鎚戰士", "hammerer"),
    ("重锤手", "hammerer"),
    ("錬金術師", "alchemist"),
    ("鍊金術師", "alchemist"),
    ("長槍兵", "lancer"),
    ("长枪兵", "lancer"),
    ("附魔师", "enchanter"),
    ("附魔師", "enchanter"),
    ("雙劍士", "dual_blader"),
    ("雷电法师", "lightning_mage"),
    ("雷術師", "lightning_mage"),
    ("雷電法師", "lightning_mage"),
    ("鞭术师", "whip_master"),
    ("鞭術師", "whip_master"),
    ("風暴法師", "wind_mage"),
    ("風術師", "wind_mage"),
    ("飓风法师", "wind_mage"),
    ("食人魔", "ogre"),
    ("騎兵", "cavalry_knight"),
    ("騎士", "knight"),
    ("驅魔師", "exorcist"),
    ("驱魔师", "exorcist"),
    ("骑兵", "cavalry_knight"),
    ("骑士", "knight"),
    ("鬼怪", "dokkaebi"),
    ("魔剑士", "magic_knight"),
    ("魔剣士", "magic_knight"),
    ("魔劍士", "magic_knight"),
    ("黑魔法师", "dark_mage"),
    ("黑魔法師", "dark_mage"),
    ("黒魔術師", "dark_mage"),
    ("강시", "jiangshi"),
    ("검사", "swordman"),
    ("격투가", "fighter"),
    ("결계사", "barrier_magician"),
    ("곡예사", "circus_blade"),
    ("공성병", "siege_breaker"),
    ("광대", "clown"),
    ("광전사", "berserker"),
    ("궁수", "archer"),
    ("그림자술사", "shadowmancer"),
    ("기병", "cavalry_knight"),
    ("기사", "knight"),
    ("네크로맨서", "necromancer"),
    ("늑대인간", "werewolf"),
    ("닌자", "ninja"),
    ("도깨비", "dokkaebi"),
    ("도박사", "gambler"),
    ("도사", "taoist"),
    ("독침술사", "poison_dart_hunter"),
    ("듀얼 블레이더", "dual_blader"),
    ("드루이드", "druid"),
    ("마검사", "magic_knight"),
    ("모래술사", "sand_mage"),
    ("몽마", "nightmare"),
    ("몽크", "monk"),
    ("무녀", "pythoness"),
    ("무희", "dancer"),
    ("바람술사", "wind_mage"),
    ("방패병", "shield_bearer"),
    ("백마술사", "white_mage"),
    ("번개술사", "lightning_mage"),
    ("봉술사", "pole_warrior"),
    ("부두술사", "voodoo_shaman"),
    ("부메랑 헌터", "boomerang_hunter"),
    ("사냥꾼", "hunter"),
    ("석궁병", "crossbowman"),
    ("성직자", "priest"),
    ("소총수", "soldier"),
    ("수호령", "guardian_spirit"),
    ("악마", "demon"),
    ("안드로이드", "android"),
    ("얼음술사", "ice_mage"),
    ("엑소시스트", "exorcist"),
    ("역병의사", "plague_doctor"),
    ("연금술사", "alchemist"),
    ("오우거", "ogre"),
    ("요리사", "chef"),
    ("유령", "ghost"),
    ("음유시인", "bard"),
    ("이단심문관", "inquisitor"),
    ("인챈터", "enchanter"),
    ("정령사", "spirit_caller"),
    ("죄수", "prisoner"),
    ("중보병", "hammerer"),
    ("창술사", "lancer"),
    ("채찍술사", "whip_master"),
    ("처형인", "executioner"),
    ("총잡이", "gunner"),
    ("폭탄병", "bomber"),
    ("화염술사", "pyromancer"),
    ("환영술사", "illusionist"),
    ("흑마술사", "dark_mage"),
    ("흡혈귀", "vampire"),
    ("히트맨", "hitman"),
];

/// 스탯 표시명 -> diff 축 (0공격 1주문력 2체력 3방어 4마저 5이속 6공속 7사거리)
pub static STATNAME2AXIS: &[(&str, usize)] = &[
    ("AD (Dano de Ataque)", 0),
    ("AP (Poder de Habilidade)", 1),
    ("Aanvalskracht", 0),
    ("Aanvalssnelheid", 6),
    ("Ability Power", 1),
    ("Alcance", 7),
    ("Angriff", 0),
    ("Armadura", 3),
    ("Armor", 3),
    ("Armure", 3),
    ("Attack", 0),
    ("Attack Speed", 6),
    ("Bereik", 7),
    ("Bewegingssnelheid", 5),
    ("Büyü Gücü", 1),
    ("Büyü direnci", 4),
    ("Can", 2),
    ("Giáp", 3),
    ("HP", 2),
    ("Hareket Hızı", 5),
    ("Health", 2),
    ("Ikaika Hoʻouka", 0),
    ("Kháng Phép", 4),
    ("Kūʻē Kilokilo", 4),
    ("Lauftempo", 5),
    ("Laulā Hoʻouka", 7),
    ("Levenspunten", 2),
    ("Magic Resist", 4),
    ("Magieresistenz", 4),
    ("Magieweerstand", 4),
    ("Mana Kilokilo", 1),
    ("Menzil", 7),
    ("Moc umiejętności", 1),
    ("Movement Speed", 5),
    ("Máu", 2),
    ("Māmā Hoʻouka", 6),
    ("Māmā Neʻe", 5),
    ("Obrażenia od ataku", 0),
    ("Odporność na magię", 4),
    ("Ola", 2),
    ("Pale", 3),
    ("Pancerz", 3),
    ("Poder de Ataque", 0),
    ("Poder de Habilidad", 1),
    ("Poder de Habilidade", 1),
    ("Points de vie", 2),
    ("Portée", 7),
    ("Puissance d'attaque", 0),
    ("Puissance magique", 1),
    ("Range", 7),
    ("Reichweite", 7),
    ("Resistencia mágica", 4),
    ("Resistência mágica", 4),
    ("Résistance magique", 4),
    ("Saldırı Gücü", 0),
    ("Saldırı Hızı", 6),
    ("Savunma", 3),
    ("Szybkość ataku", 6),
    ("Szybkość ruchu", 5),
    ("Sức Mạnh Công Kích", 0),
    ("Sức Mạnh Phép Thuật", 1),
    ("Tempo", 6),
    ("Tầm Đánh", 7),
    ("Tốc Độ Di Chuyển", 5),
    ("Tốc Độ Đánh", 6),
    ("Velocidad Movimiento", 5),
    ("Velocidad de Ataque", 6),
    ("Velocidade de Ataque", 6),
    ("Velocidade de Movimento", 5),
    ("Verdediging", 3),
    ("Vermogenskracht", 1),
    ("Verteidigung", 3),
    ("Vida", 2),
    ("Vitesse d'attaque", 6),
    ("Vitesse déplacement", 5),
    ("Zasięg ataku", 7),
    ("Zauberkraft", 1),
    ("Zdrowie", 2),
    ("Броня", 3),
    ("Дальность", 7),
    ("Здоровье", 2),
    ("Сила атаки", 0),
    ("Сила умений", 1),
    ("Скорость атаки", 6),
    ("Скорость передвижения", 5),
    ("Сопротивление магии", 4),
    ("ความเร็วเคลื่อนที่", 5),
    ("ความเร็วโจมตี", 6),
    ("ต้านทานเวท", 4),
    ("พลังชีวิต", 2),
    ("พลังเวท", 1),
    ("พลังโจมตี", 0),
    ("ระยะโจมตี", 7),
    ("เกราะ", 3),
    ("体力", 2),
    ("射程", 7),
    ("护甲", 3),
    ("攻击力", 0),
    ("攻击距离", 7),
    ("攻击速度", 6),
    ("攻撃力", 0),
    ("攻撃速度", 6),
    ("攻擊距離", 7),
    ("攻擊速度", 6),
    ("法术强度", 1),
    ("物理攻擊", 0),
    ("物理防禦", 3),
    ("生命值", 2),
    ("移动速度", 5),
    ("移動速度", 5),
    ("防御力", 3),
    ("魔法力", 1),
    ("魔法抗性", 4),
    ("魔法抵抗力", 4),
    ("魔法攻擊", 1),
    ("魔法防禦", 4),
    ("공격력", 0),
    ("공격속도", 6),
    ("마법저항력", 4),
    ("방어력", 3),
    ("사거리", 7),
    ("이동속도", 5),
    ("주문력", 1),
    ("체력", 2),
];
