// 자동 생성 — 챔피언 id -> 한글 표시명. 소스 = bundle champion.i18n (ko.description.<id>.name).
// 직접 수정 금지. 없는 id(모드챔프 등)는 id 를 그대로 표시.
pub static CHAMP_KR: &[(&str, &str)] = &[
    ("android", "안드로이드"),
    ("archer", "궁수"),
    ("bard", "음유시인"),
    ("barrier_magician", "결계사"),
    ("berserker", "광전사"),
    ("bomber", "폭탄병"),
    ("boomerang_hunter", "부메랑 헌터"),
    ("cavalry_knight", "기병"),
    ("chef", "요리사"),
    ("circus_blade", "곡예사"),
    ("clown", "광대"),
    ("dancer", "무희"),
    ("dark_mage", "흑마술사"),
    ("demon", "악마"),
    ("dokkaebi", "도깨비"),
    ("druid", "드루이드"),
    ("dual_blader", "듀얼 블레이더"),
    ("enchanter", "인챈터"),
    ("executioner", "처형인"),
    ("exorcist", "엑소시스트"),
    ("fighter", "격투가"),
    ("gambler", "도박사"),
    ("ghost", "유령"),
    ("guardian_spirit", "수호령"),
    ("gunner", "총잡이"),
    ("hammerer", "중보병"),
    ("hitman", "히트맨"),
    ("hunter", "사냥꾼"),
    ("ice_mage", "얼음술사"),
    ("illusionist", "환영술사"),
    ("inquisitor", "이단심문관"),
    ("jiangshi", "강시"),
    ("knight", "기사"),
    ("lancer", "창술사"),
    ("lightning_mage", "번개술사"),
    ("magic_knight", "마검사"),
    ("monk", "몽크"),
    ("necromancer", "네크로맨서"),
    ("ninja", "닌자"),
    ("ogre", "오우거"),
    ("plague_doctor", "역병의사"),
    ("poison_dart_hunter", "독침술사"),
    ("pole_warrior", "봉술사"),
    ("priest", "성직자"),
    ("prisoner", "죄수"),
    ("pyromancer", "화염술사"),
    ("pythoness", "무녀"),
    ("shadowmancer", "그림자술사"),
    ("shield_bearer", "방패병"),
    ("siege_breaker", "공성병"),
    ("soldier", "소총수"),
    ("spirit_caller", "정령사"),
    ("swordman", "검사"),
    ("taoist", "도사"),
    ("vampire", "흡혈귀"),
    ("voodoo_shaman", "부두술사"),
    ("werewolf", "늑대인간"),
    ("whip_master", "채찍술사"),
    ("white_mage", "백마술사"),
    ("wind_mage", "바람술사"),
];
